[package]
name = "rt_maybe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = {version = "0.29", features = ["rwh_05"]}
wgpu = "22.1"
pollster = "0.3"
env_logger = "0.11"
bytemuck = "1.16"
flume = "0.11"
rand = "0.8"
